language: php

sudo: false

services: xvfb

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - DEPS=normal
  - DEPS=highest
  - DEPS=lowest

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/travis_phantomjs

notifications:
  email: false
  slack:
    secure: ixWu6kWtNIlzzdImpu4MdvGYpA6ZPp/dQpMAp6FDO2oHHB55J9ossBYtVtBXPCDs9OxqfQl2yqbE+TkhfIfkZqIbhvX2+CiIomvYSKZDvryUlCfbfV29behmSVIVYvg3b8Tba+nAyZeJA2guUyAy02WGr3n4I+PDgZC3Wa/mv94=

before_install:
  - travis_retry composer selfupdate

  - phantomjs --version
  - export PATH=$HOME/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs --version
  - if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $HOME/travis_phantomjs; mkdir -p $HOME/travis_phantomjs; fi
  - if [ $(phantomjs --version) != '2.1.1' ]; then travis_retry wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $HOME/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi
  - if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $HOME/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $HOME/travis_phantomjs; fi
  - phantomjs --version

install:
  - if [ "$DEPS" = "normal" ]; then travis_retry composer install --no-interaction; fi;
  - if [ "$DEPS" = "highest" ]; then travis_retry composer update --no-interaction; fi;
  - if [ "$DEPS" = "lowest" ]; then travis_retry composer update --no-interaction --prefer-lowest --prefer-stable; fi;

before_script:
  - mkdir -p build/logs
  - "export DISPLAY=:99.0"
  - sleep 3

script:
  - vendor/bin/phpunit --stop-on-error --stop-on-failure --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
